# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Erik/Desktop/NeuralNetworkHardwareAccelerator/FPGA/FPGA.srcs/sources_1/ip/fc1_weights_bram_6/fc1_weights_bram_6.xci
# IP: The module: 'fc1_weights_bram_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Erik/Desktop/NeuralNetworkHardwareAccelerator/FPGA/FPGA.srcs/sources_1/ip/fc1_weights_bram_6/fc1_weights_bram_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fc1_weights_bram_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Erik/Desktop/NeuralNetworkHardwareAccelerator/FPGA/FPGA.srcs/sources_1/ip/fc1_weights_bram_6/fc1_weights_bram_6.xci
# IP: The module: 'fc1_weights_bram_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Erik/Desktop/NeuralNetworkHardwareAccelerator/FPGA/FPGA.srcs/sources_1/ip/fc1_weights_bram_6/fc1_weights_bram_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fc1_weights_bram_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
